### ISSUE TITLE
Command "menu" is not defined

### ISSUE THREAD

**Issue by scottybo** [DivineOmega/artisan-menu#1]
I guess something is missing from your installation instructions?

**Comment by DivineOmega** [comment]
Might be that the service provider is not being auto discovered. What version of Laravel are you running?

**Comment by scottybo** [comment]
5.4

**Comment by DivineOmega** [comment]
Ah, package discovery wasn't a part of Laravel 5.4 it seems.

Could you add `DivineOmega\ArtisanMenu\Providers\ArtisanMenuServiceProvider::class` to the `providers` array in your `config/app.php` file? That should solve it for you.

**Comment by DivineOmega** [comment]
@scottybo Did this work for you?
